@startuml Use Case Diagram
left to right direction
actor "User" as user
rectangle "GoCamply System" as GoCamplySystem {    
    usecase "Register" as register
    usecase "Login" as login
    usecase "Logout" as logout
    usecase "View Campgrounds" as viewCampgrounds
    usecase "Manage Appointments (Get, Create, Update, Delete)" as manageAppt
    usecase "Manage Campgrounds (Get, Create, Update, Delete)" as manageCampground
    usecase "Manage Favorite Campgrounds (Favorite, Unfavorite, Get favorited)" as favoriteCampground
    usecase "Get Availability" as getAvailability
}

user -- register
user -- viewCampgrounds
user -- manageAppt
user -- favoriteCampground
user -- login
user -- logout
user -- getAvailability

actor "Admin" as admin
register -- admin
login -- admin
logout -- admin
manageCampground -- admin
manageAppt -- admin

@enduml